"""
tests/test_scalar_correction.py
───────────────────────────────
Tests for `scripts/apply_golf_scalar_correction.py` — the JDAY scalar re-book.

The bug this file exists to prevent is one I made while writing the script: a
settled row carries VOID in **two** fields, and the consumers disagree about
which they read. `p017_checkpoint.tournament_stat` keys off **`action`**;
trade_store and the dashboard key off `outcome`. The first pass set only
`outcome`, so the row read WIN everywhere except the one place that decides the
gate — the gate still counted it as a void and the edge did not move.
"""
import importlib.util
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

_SPEC = importlib.util.spec_from_file_location(
    "apply_scalar",
    Path(__file__).resolve().parent.parent / "scripts"
    / "apply_golf_scalar_correction.py")
ac = importlib.util.module_from_spec(_SPEC)
_SPEC.loader.exec_module(ac)


def _buggy_row():
    return {"pod_id": "P-017", "market_id": ac.MARKET_ID, "action": "VOID",
            "outcome": "VOID", "result": "void", "pnl_usd": -0.53,
            "resolution_source": "kalshi_withdrawn",
            "position_size_usd": 10.0, "fill_price": 0.23}


def _write(tmp_path, rows):
    p = tmp_path / "trade_log.jsonl"
    p.write_text("".join(json.dumps(r) + "\n" for r in rows))
    return p


def _run(path, *args):
    return ac.main.__wrapped__(*args) if hasattr(ac.main, "__wrapped__") else None


def test_correction_sets_BOTH_action_and_outcome():
    """The regression. `action` is what the P-017 gate reads."""
    assert ac.CORRECTED["action"] == "WIN"
    assert ac.CORRECTED["outcome"] == "WIN"


def test_buggy_signature_requires_both_fields():
    assert ac.BUGGY["action"] == "VOID" and ac.BUGGY["outcome"] == "VOID"


def test_recognises_the_original_buggy_row():
    assert ac.is_buggy(_buggy_row())
    assert not ac.is_corrected(_buggy_row())


def test_recognises_the_half_corrected_row_so_the_job_can_be_finished():
    """The state the incomplete first pass left on the droplet."""
    r = _buggy_row()
    r.update({"outcome": "WIN", "resolution_source": "kalshi_scalar_corrected"})
    assert ac.is_buggy(r), "must be able to finish a half-applied correction"
    assert not ac.is_corrected(r)


def test_fully_corrected_row_is_a_no_op():
    r = _buggy_row()
    r.update(ac.CORRECTED)
    assert ac.is_corrected(r)


def test_an_unrelated_row_is_refused():
    r = _buggy_row()
    r.update({"action": "LOSS", "outcome": "LOSS",
              "resolution_source": "kalshi_settled"})
    assert not ac.is_buggy(r) and not ac.is_corrected(r)


def test_allow_list_is_exactly_one_market():
    assert ac.MARKET_ID == "KXPGATOP20-3MO26-JDAY"
    assert ac.EXPECTED == 1
    assert not ac.is_target({"market_id": "KXPGATOP20-3MO26-OTHER"})
    assert ac.is_target({"market_id": ac.MARKET_ID})
    assert ac.is_target({"market_ticker": ac.MARKET_ID})


def test_corrected_pnl_matches_the_committed_audit_record():
    """The numbers must agree with research/corrections/*.jsonl, which was
    generated by a script that never mutates history."""
    rec = json.loads((Path(__file__).resolve().parent.parent / "research"
                      / "corrections"
                      / "P-017_scalar_corrections_20260726.jsonl").read_text()
                     .splitlines()[0])
    assert ac.CORRECTED["pnl_usd"] == rec["corrected_pnl_usd"] == -0.10
    assert ac.CORRECTED["pnl_gross_usd"] == rec["corrected_pnl_gross_usd"] == 0.43
    assert ac.CORRECTED["settlement_value"] == rec["settlement_value"] == 0.24
