#!/usr/bin/env python3
"""
scripts/apply_golf_scalar_correction.py
───────────────────────────────────────
Apply the JDAY scalar re-book to the live trade log.

`KXPGATOP20-3MO26-JDAY` settled `result="scalar"` with
`settlement_value_dollars = 0.24` — a **partial payout, not a refund** — and the
pre-fix settler booked it VOID at $0.00. Correct is gross **+$0.43**, net
**−$0.10** (not −$0.53), and the row moves from *excluded* (VOID) to *counted*
in the P-017 gate sample.

The audit record already exists
(`research/corrections/P-017_scalar_corrections_20260726.jsonl`, generated by
`scripts/backfill_golf_scalar_corrections.py`, which never mutates history).
**This script is the deliberate, separate step that rewrites the live book**, and
it carries the same discipline as `undo_p017_spurious_voids.py`:

  * a narrow allow-list — it will only ever touch the ONE market_id below;
  * it **refuses** unless exactly one matching row is found;
  * it refuses unless that row still carries the buggy signature
    (`outcome=VOID`, `resolution_source=kalshi_withdrawn`), so a second run is a
    no-op rather than a double-correction;
  * every non-matching line is written back **byte-identical** — parsed rows are
    never re-serialised;
  * it backs the log up first, writes via a temp file, and fsyncs.

**Stop the service before running.** A live writer appending mid-rewrite would
lose rows:

    systemctl stop betting-pod-shop
    ./venv/bin/python -m scripts.apply_golf_scalar_correction --dry-run
    ./venv/bin/python -m scripts.apply_golf_scalar_correction --apply
    systemctl start betting-pod-shop

Verified scope 2026-07-26: this is the ONLY row carrying the buggy signature
across the active log and all nine archives.
"""
from __future__ import annotations

import argparse
import json
import os
import shutil
import sys
import tempfile
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict

MARKET_ID = "KXPGATOP20-3MO26-JDAY"          # the allow-list, all of it
EXPECTED = 1

# The row is settled-VOID in TWO fields, and the consumers disagree about which
# they read: `scripts/p017_checkpoint.tournament_stat` keys off **`action`**,
# while trade_store and the dashboard key off `outcome`. The first pass of this
# script set only `outcome`, so the row read WIN everywhere except the one place
# that decides the gate — the same "right field, wrong call path" failure this
# repo keeps producing. Both are set now, and a test asserts it.
BUGGY = {"action": "VOID", "outcome": "VOID",
         "resolution_source": "kalshi_withdrawn"}
# The state that incomplete first pass left behind. Accepted as a source state so
# the job can be finished; anything else is refused.
PARTIAL = {"action": "VOID", "outcome": "WIN",
           "resolution_source": "kalshi_scalar_corrected"}
CORRECTED: Dict[str, Any] = {
    "action": "WIN",
    "outcome": "WIN",
    "result": "scalar",
    "pnl_usd": -0.10,
    "pnl_gross_usd": 0.43,
    "fees_usd": 0.5332,
    "settlement_kind": "scalar_partial",
    "settlement_value": 0.24,
    "resolution_source": "kalshi_scalar_corrected",
    "correction_note": ("re-booked 2026-07-28: scalar is a PARTIAL PAYOUT at "
                        "settlement_value_dollars, not a refunded void. Audit "
                        "record: research/corrections/"
                        "P-017_scalar_corrections_20260726.jsonl"),
}


def is_target(rec: Dict[str, Any]) -> bool:
    mid = rec.get("market_id") or rec.get("market_ticker")
    return mid == MARKET_ID


def _matches(rec: Dict[str, Any], sig: Dict[str, str]) -> bool:
    return all(str(rec.get(k, "")).upper() == v.upper() for k, v in sig.items())


def is_corrected(rec: Dict[str, Any]) -> bool:
    """Already in the target state — the script must then be a no-op."""
    return (_matches(rec, {"action": "WIN", "outcome": "WIN"})
            and str(rec.get("resolution_source")) == "kalshi_scalar_corrected")


def is_buggy(rec: Dict[str, Any]) -> bool:
    """A source state this script knows how to correct."""
    return _matches(rec, BUGGY) or _matches(rec, PARTIAL)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--log-path", type=Path,
                    default=Path("data/trade_logs/trade_log.jsonl"))
    ap.add_argument("--apply", action="store_true",
                    help="write the correction (default is a dry run)")
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args()

    log = args.log_path
    if not log.exists():
        print(f"ERROR: {log} not found", file=sys.stderr)
        return 2

    out_lines, targets = [], []
    with open(log, encoding="utf-8", errors="ignore") as fh:
        for raw in fh:
            s = raw.rstrip("\n")
            if not s.strip():
                continue
            try:
                rec = json.loads(s)
            except json.JSONDecodeError:
                out_lines.append(s)         # preserved verbatim
                continue
            if is_target(rec):
                targets.append((len(out_lines), rec, s))
                out_lines.append(s)         # placeholder; replaced below
            else:
                out_lines.append(s)         # byte-identical passthrough

    print(f"log            : {log}")
    print(f"rows           : {len(out_lines)}")
    print(f"rows matching {MARKET_ID}: {len(targets)} (expected {EXPECTED})")

    if len(targets) != EXPECTED:
        print(f"\nREFUSING: expected exactly {EXPECTED} matching row, found "
              f"{len(targets)}. Investigate before rerunning.", file=sys.stderr)
        return 3

    idx, rec, _raw = targets[0]
    if is_corrected(rec):
        print("\n  already corrected — nothing to do (idempotent no-op)")
        return 0
    if not is_buggy(rec):
        print(f"\nREFUSING: the row does not carry the buggy signature "
              f"{BUGGY} — it reads outcome={rec.get('outcome')!r}, "
              f"resolution_source={rec.get('resolution_source')!r}. Either it "
              "is already corrected (this script is a no-op) or something else "
              "changed it.", file=sys.stderr)
        return 4

    print(f"\n  before : action={rec.get('action')} outcome={rec.get('outcome')} "
          f"pnl={rec.get('pnl_usd')} source={rec.get('resolution_source')}")
    fixed = dict(rec)
    fixed.update(CORRECTED)
    print(f"  after  : action={fixed['action']} outcome={fixed['outcome']} "
          f"pnl={fixed['pnl_usd']} gross={fixed['pnl_gross_usd']} "
          f"source={fixed['resolution_source']}")
    print(f"  delta  : {fixed['pnl_usd'] - float(rec.get('pnl_usd') or 0):+.2f} USD"
          "   and the row moves VOID(excluded) -> WIN(counted) in the gate")

    if not args.apply or args.dry_run:
        print("\n[dry-run] nothing written. Re-run with --apply to commit.")
        return 0

    out_lines[idx] = json.dumps(fixed, default=str)

    backup = log.with_suffix(
        f".jsonl.bak_scalar_correction_{datetime.now(timezone.utc):%Y%m%dT%H%M%SZ}")
    shutil.copy2(log, backup)
    print(f"\nbackup         : {backup}")

    fd, tmp = tempfile.mkstemp(dir=str(log.parent), suffix=".tmp")
    with os.fdopen(fd, "w", encoding="utf-8") as fh:
        for s in out_lines:
            fh.write(s + "\n")
        fh.flush()
        os.fsync(fh.fileno())
    os.replace(tmp, log)
    print(f"rows out       : {len(out_lines)}  (1 row corrected in place)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
